docker rm -f $(docker ps -a -f name=scoring_enigne -q)

# Load Config
. ./config.default || . ../../config.default

echo "GCP_PROJECT_ID: $TF_VAR_GCP_PROJECT_ID"

docker run -it --name scoring_enigne \
--env GCP_PROJECT_ID=$TF_VAR_GCP_PROJECT_ID \
--env DATAFLOW_REGION=$TF_VAR_DATAFLOW_REGION \
--env DATAFLOW_GCS_BUCKET=$TF_VAR_DATAFLOW_GCS_BUCKET \
--env PUBSUB_TOPIC_TEXT_INPUT=$TF_VAR_PUBSUB_TOPIC_TEXT_INPUT \
--env PUBSUB_TOPIC_TEXT_SCORED=$TF_VAR_PUBSUB_TOPIC_TEXT_SCORED \
--env PUBSUB_TOPIC_TOXIC=$TF_VAR_PUBSUB_TOPIC_TOXIC \
--env BIGQUERY_DATASET=$TF_VAR_BIGQUERY_DATASET \
--env BIGQUERY_TABLE=$TF_VAR_BIGQUERY_TABLE \
--env WINDOW_DURATION_SECONDS=$TF_VAR_WINDOW_DURATION_SECONDS \
--env WINDOW_SLIDING_SECONDS=$TF_VAR_WINDOW_SLIDING_SECONDS \
--env DATAFLOW_RUNNER=DirectRunner \
--env TF_VAR_TOXIC_USER_THRESHOLD=$TF_VAR_TOXIC_USER_THRESHOLD \
--env TF_VAR_PERSPECTIVE_API_KEY=$TF_VAR_PERSPECTIVE_API_KEY \
scoring_engine
